"use client";

import { useEffect, useState } from "react";
import { Loader2, RotateCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getRestaurantReservation, listRestaurantNotificationHistory, resendRestaurantReservationConfirmation, type RestaurantNotificationLog, type RestaurantReservation } from "@/app/admin/lib/adminApi";
import { notify } from "@/lib/notify";

const eventLabel: Record<string, string> = { RESTAURANT_RESERVATION_CREATED: "Solicitud recibida", RESTAURANT_RESERVATION_CONFIRMED: "Reserva confirmada", RESTAURANT_RESERVATION_UPDATED: "Reserva actualizada", RESTAURANT_RESERVATION_CANCELLED: "Reserva cancelada", RESTAURANT_RESERVATION_REMINDER: "Recordatorio" };
const maskRecipient = (value: string | null) => { if (!value) return "—"; if (value.includes("@")) { const [name, domain] = value.split("@"); return `${name.slice(0, 2)}•••@${domain}`; } return `${value.slice(0, 3)}•••${value.slice(-2)}`; };
const format = (value: string | null) => value ? new Intl.DateTimeFormat("es-BO", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";

export function RestaurantNotificationPanel({ reservationId }: { reservationId: number }) {
  const [logs, setLogs] = useState<RestaurantNotificationLog[]>([]); const [reservation, setReservation] = useState<RestaurantReservation | null>(null); const [loading, setLoading] = useState(true); const [resending, setResending] = useState(false);
  const load = async () => { setLoading(true); try { const [current, history] = await Promise.all([getRestaurantReservation(reservationId), listRestaurantNotificationHistory(reservationId)]); setReservation(current); setLogs(history); } catch (error) { await notify.error(error instanceof Error ? error.message : "No pudimos cargar el historial de notificaciones."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [reservationId]);
  const canResend = reservation?.status === "PENDING" || reservation?.status === "CONFIRMED";
  const resend = async () => { setResending(true); try { const result = await resendRestaurantReservationConfirmation(reservationId); const sent = result.results.filter((entry) => entry.status === "SENT").length; await notify.success(sent ? `Reenvío procesado en ${sent} canal(es).` : "No había canales disponibles para el reenvío."); await load(); } catch (error) { await notify.error(error instanceof Error ? error.message : "No pudimos reenviar la reserva."); } finally { setResending(false); } };
  return <section className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-slate-950">Historial de notificaciones</h2><p className="mt-1 text-sm text-slate-500">Resultados de entrega por canal.</p></div>{canResend ? <Button size="sm" variant="outline" disabled={resending} onClick={() => void resend()}><RotateCw className="mr-2 h-4 w-4"/>{resending ? "Reenviando…" : "Reenviar"}</Button> : null}</div>{loading ? <div className="flex justify-center py-6"><Loader2 className="h-5 w-5 animate-spin text-admin-brand" /></div> : <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="border-b text-xs uppercase tracking-wide text-slate-500"><tr><th className="pb-2">Evento</th><th className="pb-2">Canal</th><th className="pb-2">Destino</th><th className="pb-2">Resultado</th><th className="pb-2">Fecha</th></tr></thead><tbody>{logs.map((log) => <tr key={log.id} className="border-b border-slate-100"><td className="py-3">{eventLabel[log.event]}</td><td>{log.channel === "WHATSAPP" ? "WhatsApp" : "Correo"}</td><td>{maskRecipient(log.recipient)}</td><td><span className={log.status === "SENT" ? "text-emerald-700" : log.status === "FAILED" ? "text-red-700" : "text-slate-600"}>{log.status === "SENT" ? "Enviado" : log.status === "FAILED" ? log.error_message || "Falló" : log.status === "SKIPPED" ? "Omitido" : "Pendiente"}</span></td><td>{format(log.sent_at || log.created_at)}</td></tr>)}{!logs.length ? <tr><td colSpan={5} className="py-6 text-center text-slate-500">Aún no hay mensajes registrados.</td></tr> : null}</tbody></table></div>}</section>;
}
