export const mockData = {
  business: {
    name: "The Modern Barber",
    address: "123 Style St, Metropolis",
    phone: "(555) 123-4567",
    email: "contact@modernbarber.com",
    rating: 4.8,
    reviews: 250,
    amenities: ["Free Parking", "Free WiFi", "Wheelchair Accessible"],
    hours: [
      { day: "Monday", hours: "Closed" },
      { day: "Tuesday", hours: "9:00 AM - 7:00 PM" },
      { day: "Wednesday", hours: "9:00 AM - 7:00 PM" },
      { day: "Thursday", hours: "10:00 AM - 8:00 PM" },
      { day: "Friday", hours: "10:00 AM - 8:00 PM" },
      { day: "Saturday", hours: "9:00 AM - 6:00 PM" },
      { day: "Sunday", hours: "11:00 AM - 5:00 PM" },
    ],
    social: {
      facebook: "#",
      instagram: "#",
      twitter: "#",
    },
  },
  services: [
    {
      id: "1",
      name: "Classic Haircut",
      description: "A timeless cut tailored to your style. Includes wash and style.",
      price: 40,
      duration: 45, // in minutes
      category: "Haircuts",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAwfzrcohMMURu6ETOGEzhGsdVl0xaCEHQlZPyqgnBZRmF5A0N5LawB7eddbGeCF2gYHS4uRH7UbAMWl02SunqnyscsWnlhMVi_8cEBT-7p_S94oTM4yB864YzYIqY9aDMMAs_Tw8dc1AD64Z0339auySnZnEE3Srpyfd_Qbfb55soEOmTshoTi6-TGOIRj9icxRavJRlyLTPFIy0RgacopTyQJTWtF82Hs4OQKfX-RSGlXja967U-VPlT4tdfmsO5An9CgepQN6NE",
    },
    {
      id: "2",
      name: "Beard Trim & Shape",
      description: "Precision trimming and shaping for a perfectly groomed beard.",
      price: 25,
      duration: 30,
      category: "Beard Trims",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBz0jPMXSHyzaCbI4ZZJPydx0BsgZuCUNXec0v363c8WlZlRybfg6Qp0EA8T8T-_pOaF5av6vrzSbb3NFUm2teEzZ5Z4lgqz4LOsKKfhW_1EPIHdkZFh6_B4DDAXC-ZNVZ8dlrzX3jzWMcQPlKka9Xa2X5vMNunXN8YOb57ohEZ3WzvO3DcpPZtizrYziv0uQAvSqGRmWdDBFm5iENvFScZG_RV0vSPxNU5YJVZRRZ4ZQHgYM2-LKJLKA_JQ7DuTGrgWopcDEcYfxA",
    },
    {
      id: "3",
      name: "The Full Works",
      description: "The ultimate grooming package: haircut, beard trim, and hot towel shave.",
      price: 75,
      duration: 90,
      category: "Packages",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBsi82uREy-Y6O86BwhePA87bp00_SQyYMz5O3Cl6jM82nr04amrL4xsMo9hXccdvlDt-lrxpfhPg_vDezM2s2YqygmCbuthKOdABCTebEGj7Zbi8Qgxl08xNnVZf2rWR2OsjFmltlWMEh9W9zFiJnnM6OzBKtZOpyNgEaal704r6nWehMY6DwAq3VE3EVwksnhfpvZgozXQk-h8d17lgReLxyBSUhvnlE2YJTglnjgxJ0Rmy4YBr9DV2lsbxCUyVw6wbyFptMqz1I",
    },
     {
      id: "4",
      name: "Full Color Service",
      description: "Single process all-over color from root to tip.",
      price: 120,
      duration: 90,
      category: "Coloring",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBsi82uREy-Y6O86BwhePA87bp00_SQyYMz5O3Cl6jM82nr04amrL4xsMo9hXccdvlDt-lrxpfhPg_vDezM2s2YqygmCbuthKOdABCTebEGj7Zbi8Qgxl08xNnVZf2rWR2OsjFmltlWMEh9W9zFiJnnM6OzBKtZOpyNgEaal704r6nWehMY6DwAq3VE3EVwksnhfpvZgozXQk-h8d17lgReLxyBSUhvnlE2YJTglnjgxJ0Rmy4YBr9DV2lsbxCUyVw6wbyFptMqz1I",
    },
  ],
  team: [
    {
      id: "1",
      name: "Alex Johnson",
      title: "Master Barber",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBwVmuXA9ZvhYcOr_s8uL37G-Xhhe5Xo_A8AjuhbIeHbusQndZyKQQKU81IeSoEi8jX043jbtRfcIIC_2e7GMeb5XsfnNXbK1PSjjBfK8tCR3DwSmXPD3aZe1FTrzPu-eYPVwvvqq6NckplIjT5zCrYMlAhfc5XPbhte_2eoc2sLYbkFyAtsK6QWCIq8mCZpBK_k7RGuwXoGdALQ9OfuP0-bWLNn4UDTeGxAtmmJEznTRn5xf2KFvWR5aBv0d9ZQj-XYQ29s2tbV-4",
      rating: 4.9,
      reviews: 124,
      availability: "Today at 3:00 PM",
    },
    {
      id: "2",
      name: "Maria Garcia",
      title: "Senior Stylist",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAfc6SWjIW1NZ-1fVqgR1P88PfOKfDP0_GGRVya33uVgy2uFsrNgxH_856fmwWYJ3i386sqsLh0QayoM23r0rlWa1TLAyEXw6uTvFQM8KYc7kPbXTATI2FS6xQk4374Z6LMSH8pU6_oSSuUWTtVQPcgkhkgzwbV0yYoJ3s858KuTCYYfMrLd3pQhoRAjhRWiJzsKPrO08p5Qy0Hm8vaI_lB2SKeE5xWETU_Va4iAzqDNp2eF267O2pP4By1fae6iwbl_etdN7CxMUA",
      rating: 4.8,
      reviews: 98,
      availability: "Today at 4:30 PM",
    },
    {
      id: "3",
      name: "Sam Chen",
      title: "Barber",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB-2L8B7n0gp9Y9Kks6ziPjRdTj_6L3-sY-9orR_UMuwfwyxsKqwqorC4qBMFF2G9bCFmbUcXV5lwP94lUwOGejhPZ9zABPyvLB0K-T05VbxSR33oigcAmgRiJV-ULnJtnu0Af__Z0fyptQ9hmBfy_KKRr0yoZRSnQNL8O76o8NYsnbYCRQmOBc2TGhQyD3dK7IWsNHQ7renoZFhPRPkbtY1OSTnYQq4H-BzkfVZTrmiUzF0hfRb1_ueWsHyMOUcuq9jlLoca5SMEI",
      rating: 4.7,
      reviews: 75,
      availability: "Tomorrow at 10:00 AM",
    },
    {
      id: "4",
      name: "Chloe Davis",
      title: "Junior Stylist",
      image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC9tYGtAvKLIJcipzxlwhNbSwi-feyEfbsv8UFZtYI9RCxaWU-VSxJtOyc1RFPmN-8WMEVmIVZfByqP2pAnN5eRdbkdnohT9cPlSmoyQ_zjJoVG4o8S3MaDkR93aVZ2FGCKw8df7Qotvvy2m2xzDNMD-S2FGTQykWVMjV49eDzvVFJEWjFa4oFsJXLvpftJMHnVYhrY-9D0vUkSBh6dmzlGC7Be6GLR4w0e_2Fl7utmrphBe1ZIWwAk5Ud-f2y0DaHjN7bnTXfTYGM",
      rating: 5.0,
      reviews: 32,
      availability: "Tomorrow at 11:30 AM",
    },
  ],
  reviews: [
    {
      id: "1",
      author: "David Lee",
      rating: 5,
      comment: "Absolutely the best haircut I've had in years. The attention to detail is incredible. I'll definitely be back!",
      avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAH8bZ_RX_qblI1dNT__kKNRvxxdanUdbRIVOsvdPcQLhYYRNoipLVnlQcJdqezvRlalG3jerUaXWu2_Pfi6_GgMK-Z4haXvB3htZdcNKdudYLWE5tDbGjkGBm1z4sVzj-uX_D8S3ZZGPAChXcM9arsgTU1Ign5dlD9tCpuRiJFeRxBP_sHv__Ivz_fWa-9L_eN7GRHJPJXHng7jiqMw41Q6gTD-Ez9ebDQ1zlXS0uQ522tvDi723K42pDIXUOJBai_0J-dcAjl8qw",
    },
    {
      id: "2",
      author: "Jessica Miller",
      rating: 5,
      comment: "Maria is a true artist! She listened to what I wanted and gave me the perfect style. The salon has a great, relaxing vibe.",
      avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAwWLVblcNH7kymRrLsg_XF0iEPhZBLrCBHC8r-z1fe6tk8nozsYgCc0PMQe643ulR5vLflaRoSH8pDbBW048KluhVq5f6oa4W0uIuRvO9w6mbO2C3yp3Awe2umSNAYwgtmMesSSk_6FJV9RD5_7v13fRvShCDzf9buZjYHVV0ieHzVCk--2RPwHhcXHT3F0P6zu0IEeUscqMNZbpY3YyWmla4csJvPhJEkqjQOFDYlWQ-pxJB7WEIl6YyHZzW4rXBvmHrB3_4YOIw",
    },
  ],
  user: {
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "(555) 555-5555",
    reservations: {
      past: [
        { id: "1", service: "Classic Haircut", staff: "Alex Johnson", date: "2024-09-15", time: "2:00 PM", status: "Completed" },
      ],
      future: [
        { id: "2", service: "Beard Trim & Shape", staff: "Maria Garcia", date: "2024-11-20", time: "4:30 PM", status: "Confirmed" },
      ],
    },
  },
};
