"use client";
/* eslint-disable @next/next/no-img-element */

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AlertCircle, ArrowRight, Clock3, Loader2, Star } from "lucide-react";
import { resolveBackendUrl } from "@/lib/api-url";
import { getImageUrl } from "@/utils/image-url";
import { Button } from "@/components/ui/button";

type MenuItem = { id: number; name: string; description: string | null; price: string | null; imageUrl: string | null; isAvailable: boolean; isFeatured: boolean; preparationMinutes: number | null; dietaryLabels: string[]; allergens: string[] };
type MenuData = { restaurant: { name: string; slug: string; currency: string }; featuredItems: MenuItem[]; categories: Array<{ id: number; name: string; description: string | null; imageUrl: string | null; items: MenuItem[] }> };
const labels: Record<string, string> = { VEGETARIAN: "Vegetariano", VEGAN: "Vegano", GLUTEN_FREE: "Sin gluten", SPICY: "Picante", DAIRY_FREE: "Sin lácteos", NUT_FREE: "Sin frutos secos" };
const allergenLabels: Record<string, string> = { GLUTEN: "Gluten", DAIRY: "Lácteos", EGGS: "Huevos", PEANUTS: "Maní", TREE_NUTS: "Frutos secos", SOY: "Soya", FISH: "Pescado", SHELLFISH: "Mariscos", SESAME: "Sésamo" };
function price(value: string, currency: string) { try { return new Intl.NumberFormat("es-BO", { style: "currency", currency, maximumFractionDigits: 2 }).format(Number(value)); } catch { return `${currency} ${value}`; } }
function ItemCard({ item, currency, featured = false }: { item: MenuItem; currency: string; featured?: boolean }) { return <article className={`grid gap-4 ${featured ? "sm:grid-cols-[144px_minmax(0,1fr)]" : "sm:grid-cols-[112px_minmax(0,1fr)]"}`}><div className={`relative overflow-hidden rounded-xl bg-section ${featured ? "aspect-[4/3]" : "aspect-square"}`}>{item.imageUrl ? <img src={getImageUrl(item.imageUrl) || ""} alt={item.name} className={`h-full w-full object-cover ${!item.isAvailable ? "opacity-50" : ""}`} /> : <div className="flex h-full items-center justify-center text-xs text-text-muted">Sin imagen</div>}{!item.isAvailable && <span className="absolute inset-x-2 bottom-2 rounded-md bg-surface/95 px-2 py-1 text-center text-xs font-semibold text-text-main">No disponible temporalmente</span>}</div><div className="min-w-0"><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="text-lg font-semibold leading-snug text-text-main">{item.name}</h3>{item.price && <span className="shrink-0 text-lg font-bold text-brand">{price(item.price, currency)}</span>}</div>{item.description && <p className="mt-1 text-sm leading-6 text-text-muted">{item.description}</p>}{item.preparationMinutes !== null && <p className="mt-2 inline-flex items-center gap-1 text-xs text-text-muted"><Clock3 className="h-3.5 w-3.5"/>{item.preparationMinutes} min aprox.</p>}<div className="mt-3 flex flex-wrap gap-1.5">{item.dietaryLabels.map((label) => <span key={label} className="rounded-full bg-brand-soft-bg px-2 py-1 text-xs font-medium text-brand">{labels[label] || label}</span>)}{item.allergens.length ? <span className="w-full text-xs text-text-muted">Alérgenos: {item.allergens.map((allergen) => allergenLabels[allergen] || allergen).join(", ")}</span> : null}</div></div></article>; }
export default function PublicRestaurantMenuPage({ params }: { params: Promise<{ slug: string }> }) {
  const [data, setData] = useState<MenuData | null>(null); const [error, setError] = useState(false); const [slug, setSlug] = useState("");
  useEffect(() => { void params.then(({ slug: value }) => setSlug(value)); }, [params]);
  const load = async () => { if (!slug) return; setError(false); try { const response = await fetch(resolveBackendUrl(`/api/restaurant/public/${encodeURIComponent(slug)}/menu`), { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(); setData(payload.data); } catch { setError(true); } };
  useEffect(() => { void load(); }, [slug]);
  const anchors = useMemo(() => data?.categories.map((category) => ({ id: `category-${category.id}`, name: category.name })) ?? [], [data]);
  if (!data && !error) return <div className="flex justify-center py-24"><Loader2 className="h-7 w-7 animate-spin text-brand"/></div>;
  if (error || !data) return <main className="mx-auto max-w-3xl px-4 py-20 text-center"><AlertCircle className="mx-auto h-8 w-8 text-brand"/><h1 className="mt-4 text-2xl font-bold text-text-main">El menú todavía no está disponible.</h1><p className="mt-2 text-text-muted">Intentá de nuevo en unos instantes.</p><Button className="mt-5" onClick={() => void load()}>Reintentar</Button></main>;
  return <main className="mx-auto max-w-6xl px-4 pb-16 pt-8 sm:px-6"><header className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-brand">Carta</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-text-main sm:text-4xl">Menú de {data.restaurant.name}</h1><p className="mt-3 text-text-muted">Explorá nuestros platos y consultá directamente con el restaurante si tienes alergias o restricciones alimentarias.</p></header>{anchors.length > 1 && <nav aria-label="Categorías del menú" className="sticky top-[var(--shop-announcement-offset,0px)] z-20 -mx-4 mt-7 flex gap-2 overflow-x-auto border-y border-surface-border bg-surface/95 px-4 py-3 backdrop-blur sm:mx-0 sm:rounded-lg sm:border"><span className="sr-only">Ir a categoría</span>{anchors.map((category) => <a key={category.id} href={`#${category.id}`} className="shrink-0 rounded-full border border-surface-border px-3 py-1.5 text-sm font-medium text-text-main transition hover:border-brand hover:text-brand">{category.name}</a>)}</nav>}{data.featuredItems.length > 0 && <section className="mt-10"><div className="mb-5 flex items-center gap-2"><Star className="h-5 w-5 fill-brand text-brand"/><h2 className="text-2xl font-bold text-text-main">Destacados</h2></div><div className="grid gap-5 md:grid-cols-2">{data.featuredItems.map((item) => <div key={item.id} className="rounded-2xl border border-surface-border bg-surface p-4 shadow-card"><ItemCard item={item} currency={data.restaurant.currency} featured/></div>)}</div></section>}<section className="mt-12 space-y-12">{data.categories.map((category) => <section key={category.id} id={`category-${category.id}`} className="scroll-mt-28"><div className="mb-5 border-b border-surface-border pb-3"><h2 className="text-2xl font-bold text-text-main">{category.name}</h2>{category.description && <p className="mt-1 text-sm text-text-muted">{category.description}</p>}</div><div className="grid gap-7 md:grid-cols-2">{category.items.map((item) => <ItemCard key={item.id} item={item} currency={data.restaurant.currency}/>)}</div></section>)}</section><section className="mt-14 flex flex-col gap-4 rounded-2xl bg-section p-6 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-bold text-text-main">¿Quieres visitarnos?</h2><p className="mt-1 text-sm text-text-muted">Reserva tu mesa y disfruta la experiencia en el restaurante.</p></div><Button asChild className="shrink-0 bg-brand text-white hover:bg-brand-hover"><Link href={`/shop/${data.restaurant.slug}/reserve`}>Reservar una mesa <ArrowRight className="ml-2 h-4 w-4"/></Link></Button></section></main>;
}
