"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { cancelPublicRestaurantReservation, getPublicRestaurantReservation, type PublicRestaurantReservation } from "../../../lib/restaurantReservationsApi";

const statuses: Record<PublicRestaurantReservation["status"], string> = { PENDING: "Pendiente", CONFIRMED: "Confirmada", ARRIVED: "Tu llegada fue registrada", SEATED: "Estás en mesa", COMPLETED: "Completada", CANCELLED: "Cancelada", NO_SHOW: "No se presentó" };
function apiError(error: unknown) { const value = error as { message?: string }; return value.message || "No pudimos completar la solicitud."; }
export default function PublicRestaurantReservationDetailPage({ params }: { params: Promise<{ slug: string; code: string }> }) {
  const [reservation, setReservation] = useState<PublicRestaurantReservation | null>(null); const [error, setError] = useState<string | null>(null); const [dialog, setDialog] = useState(false); const [reason, setReason] = useState(""); const [cancelling, setCancelling] = useState(false);
  const [route, setRoute] = useState<{ slug: string; code: string } | null>(null); useEffect(() => { void params.then(setRoute); }, [params]);
  const load = async (code: string) => { try { setError(null); setReservation((await getPublicRestaurantReservation(code)).reservation); } catch (cause: unknown) { setError(apiError(cause)); } };
  useEffect(() => { if (route) void load(route.code); }, [route]);
  const cancel = async () => { if (!reservation) return; setCancelling(true); try { setReservation((await cancelPublicRestaurantReservation(reservation.code, reason || undefined)).reservation); setDialog(false); } catch (cause: unknown) { setError(apiError(cause)); } finally { setCancelling(false); } };
  if (!route || (!reservation && !error)) return <main className="flex min-h-[70vh] items-center justify-center bg-page"><Loader2 className="h-7 w-7 animate-spin text-brand" /></main>;
  if (!reservation) return <main className="mx-auto flex min-h-[70vh] max-w-xl flex-col items-center justify-center px-4 text-center text-text-main"><h1 className="text-2xl font-bold">Reserva no disponible</h1><p className="mt-2 text-text-muted">{error || "No pudimos encontrar esta reserva."}</p><Link href={`/shop/${route.slug}`} className="mt-6"><Button>Volver al restaurante</Button></Link></main>;
  return <main className="mx-auto min-h-[70vh] max-w-2xl px-4 py-8 text-text-main sm:px-6 sm:py-12"><section className="overflow-hidden rounded-2xl border border-surface-border bg-surface"><header className="bg-section p-6 sm:p-8"><p className="text-sm font-semibold text-brand">{reservation.restaurant.name}</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Tu reserva</h1><p className="mt-3 inline-flex rounded-full border border-surface-border bg-surface px-3 py-1 text-sm font-semibold">{statuses[reservation.status]}</p></header><div className="grid gap-px bg-surface-border sm:grid-cols-2">{[["Código", reservation.code], ["Fecha", reservation.date], ["Hora", reservation.time], ["Comensales", String(reservation.partySize)], ["A nombre de", reservation.customerName], ["Cancelación", reservation.canCancel ? `Hasta ${reservation.cancellationDeadline}` : "No disponible"]].map(([label, value]) => <div className="bg-surface p-5" key={label}><dt className="text-xs font-semibold uppercase tracking-wide text-text-muted">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>)}</div>{reservation.notes && <div className="border-t border-surface-border p-5"><h2 className="font-bold">Notas</h2><p className="mt-2 whitespace-pre-wrap text-sm text-text-muted">{reservation.notes}</p></div>}<div className="border-t border-surface-border p-5">{reservation.canCancel ? <Button variant="outline" className="min-h-11 border-destructive text-destructive hover:bg-destructive/10" onClick={() => setDialog(true)}>Cancelar reserva</Button> : <p className="text-sm text-text-muted">Para consultas, comunicate directamente con el restaurante.</p>}{error && <p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}</div></section><Dialog open={dialog} onOpenChange={setDialog}><DialogContent><DialogHeader><DialogTitle>¿Cancelar tu reserva?</DialogTitle><DialogDescription>Esta acción no se puede deshacer. Podés incluir un motivo para el restaurante.</DialogDescription></DialogHeader><label className="grid gap-2 text-sm font-semibold">Motivo (opcional)<textarea maxLength={500} className="min-h-20 rounded-md border border-surface-border bg-page p-3" value={reason} onChange={(e) => setReason(e.target.value)} /></label><DialogFooter><Button variant="outline" onClick={() => setDialog(false)}>Volver</Button><Button disabled={cancelling} className="bg-destructive text-white hover:bg-destructive/90" onClick={() => void cancel()}>{cancelling && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Cancelar reserva</Button></DialogFooter></DialogContent></Dialog></main>;
}
